services:
  - type: web
    name: ad-master-admin
    runtime: static
    rootDir: app
    buildCommand: bash ./scripts/build_admin_web.sh
    staticPublishPath: app/build/web
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
